name: Build Geode Mod

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build git curl

      - name: Install Geode CLI
        run: |
          curl -fsSL https://geode-sdk.org/install.sh | bash

      - name: Add Geode to PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify CLI
        run: |
          geode --version

      - name: Install SDK
        run: |
          geode sdk install

      - name: Configure
        run: |
          geode build configure

      - name: Build
        run: |
          geode build build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NoOrbsMod
          path: build/*
